enum ObjectTypes {
	PREFAB_ROOT = "prefabRoot",
	ROOT = "root",
	NODE2D = "node2D",
	SPRITE = "sprite",
	ANIMATED_SPRITE = "animatedSprite",
	TEXT = "text",
	HTML_TEXT = "htmlText",
	CONTAINER = "container",
	GRAPHICS = "graphics",
	TILING_SPRITE = "tilingSprite",
	LAYOUT2D = "layout2D",
	CELL2D = "cell2D",
	PARTICLE_EMITTER = "particleEmitter",
	SPINE = "spine",
	NINESLICE = "nineSliceSprite",
	VIEWPORT = "viewport",
	TUTORIAL = "tutorial",
	CAMERA = "camera",
	FEEDBACK = "feedback",
	SCRIPTS = "scripts",
	CTA = "cta",
	LOTTIE = "lottie",
	LAYER = "layer",
	VIDEO = "video",

	// 3D
	NODE3D = "node3D",
	// OBJECT3D = "object3D",
	BOX = "box",
	SPHERE = "sphere",
	CYLINDER = "cylinder",
	CONE = "cone",
	PLANE = "plane",
	SPRITE3D = "sprite3D",
	MESH = "mesh",
	LIGHT = "light",
	POINT_LIGHT = "pointLight",
	SPOT_LIGHT = "spotLight",
	DIRECTIONAL_LIGHT = "directionalLight",
	AMBIENT_LIGHT = "ambientLight",
	HEMISPHERE_LIGHT = "hemisphereLight",
	RECT_AREA_LIGHT = "rectAreaLight",
	PERSPECTIVE_CAMERA = "perspectiveCamera",
	MODEL = "model",
	QUARKS_PARTICLE = "quarksParticle",
	SKINNED_MESH = "skinnedMesh",
	BONE = "bone",
	INLINE_MODEL = "inlineModel",
	SHURA_PARTICLE = "shuraParticle"
}

export default ObjectTypes;
